//! Generate the symbol-row contract from its serialized Rust field names/types.
use jeryu_codegraph::SymbolRow;
use serde_json::{Value, json};

fn schema() -> Value {
    // Empty strings are accepted by SymbolRow; a contract must not invent a
    // minLength restriction. The largest u32 binds the integer domain too.
    let row = SymbolRow {
        crate_name: String::new(),
        file: String::new(),
        symbol: String::new(),
        kind: String::new(),
        is_public: false,
        line: u32::MAX,
    };
    let serialized = serde_json::to_value(row).expect("serializable symbol row");
    let fields = serialized.as_object().expect("symbol row object");
    let properties: serde_json::Map<String, Value> = fields
        .iter()
        .map(|(name, value)| {
            let property = match value {
                Value::String(_) => json!({"type": "string"}),
                Value::Bool(_) => json!({"type": "boolean"}),
                Value::Number(_) => {
                    json!({"type": "integer", "minimum": 0, "maximum": u32::MAX})
                }
                _ => panic!("unsupported symbol field type: {name}"),
            };
            (name.clone(), property)
        })
        .collect();
    json!({
        "$comment": "Generated by: cargo run --locked -p jeryu-codegraph --example symbol-schema. DO NOT EDIT.",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://git.neverhuman.org/git/jeryu/jeryu-intelligence/contracts/codegraph.schema.json",
        "title": "Codegraph symbol row",
        "type": "object",
        // Serde accepts unknown input fields; output has exactly these fields.
        "additionalProperties": true,
        "required": fields.keys().collect::<Vec<_>>(),
        "properties": properties,
    })
}

fn main() {
    println!("{}", serde_json::to_string_pretty(&schema()).unwrap());
}

#[test]
fn committed_schema_matches_the_rust_serialization_contract() {
    let committed: Value =
        serde_json::from_str(include_str!("../../../contracts/codegraph.schema.json")).unwrap();
    assert_eq!(committed, schema());
    // These valid input cases are why a schema with a `crate` field, a
    // minLength and additionalProperties=false cannot describe this Rust type.
    let input = json!({"crate_name":"", "file":"", "symbol":"", "kind":"",
        "is_public":false, "line":u32::MAX, "future_field":true});
    assert!(serde_json::from_value::<SymbolRow>(input).is_ok());
}
